# Site settings
title: Humberto Salazar
subtitle: full stack web developer
email: contacto@hsalazar.xyz
description: "..."
author: Humberto Salazar Pacios
baseurl: ""
url: "http://www.hsalazar.xyz"
twitter_username: hsalazar
github_username:  hsalazr
collections:
 - jobs
# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
production: true
exclude:
 - hsalazrio.sublime-project
 - hsalazrio.sublime-workspace
lsi: false
gems:
 - jekyll-sitemap
 - jemoji
sass:
  style: :compressed
paginate: 4
paginate_path: "/blog/page/:num"