# Site settings
title: Humberto Salazar
subtitle: cloud engineer
email: contacto@hsalazar.xyz
description: >
  Más de 9 años trabajando en el Diseño, Desarrollo, Despliegue, Explotación y Optimización de Soluciones Web y Cloud. 
  Definiciones de Arquitectura, configuración de Infraestructura en AWS automatización y de procesos de CI/CD
author: Humberto Salazar Pacios
baseurl: ""
url: "http://www.hsalazar.xyz"
twitter_username: hsalazar
github_username:  hsalazr
collections:
 - jobs
 - jobs_en
# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
excerpt_separator: <!--more-->
production: true
exclude:
 - hsalazrio.sublime-project
 - hsalazrio.sublime-workspace
lsi: false
gems:
 - jekyll-sitemap
 - jemoji
 - jekyll-paginate
sass:
  style: :compressed
paginate: 3
paginate_path: "/blog/page/:num"