# Site settings
title: Humberto Salazar
subtitle: full stack web developer
email: contacto@hsalazar.xyz
description: >
  Más de 6 años trabajando en el Diseño, Desarrollo, Despliegue, Explotación y Optimización de Soluciones Web. Desde la
  concepción de Arquitectura, configuración de Servidores hasta la Implementación de todas las capas de la Aplicación
author: Humberto Salazar Pacios
baseurl: ""
url: "http://www.hsalazar.xyz"
twitter_username: hsalazar
github_username:  hsalazr
collections:
 - jobs
# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
excerpt_separator: <!--more-->
production: true
exclude:
 - hsalazrio.sublime-project
 - hsalazrio.sublime-workspace
lsi: false
gems:
 - jekyll-sitemap
 - jemoji
 - jekyll-paginate
sass:
  style: :compressed
paginate: 3
paginate_path: "/blog/page/:num"