# Site settings
title: Humberto Salazar
subtitle: full stack web developer
email: hsalazr@gmail.com
description: "..."
author: Humberto Salazar Pacios
baseurl: ""
url: "http://hsalazr.github.io"
twitter_username: hsalazar
github_username:  hsalazr
collections:
 - jobs
# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
production: true
exclude:
 - hsalazrio.sublime-project
 - hsalazrio.sublime-workspace
lsi: false
gems:
 - jekyll-sitemap
 - jemoji
sass:
  style: :compressed