# Site settings
title: Humberto Salazar Pacios
email: hsalazr@gmail.com
description: "..."
baseurl: ""
url: "http://hsalazr.github.io"
twitter_username: hsalazar
github_username:  hsalazr

# Build settings
markdown: kramdown
permalink: pretty
